[tool.poetry]
name = "python-learn"
version = "0.1.0"
description = ""
authors = ["liuxuan <2466959245@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
